version: "3"
services:
  yzm:
    image: registry.cn-hangzhou.aliyuncs.com/zm-dev/yzm-client
    restart: always
    environment:
      - distinguish_server_address=yzm_rpc_server:8080
    ports:
      - "8102:8000"
    links:
      - yzm_rpc_server

  yzm_rpc_server:
    image: registry.cn-hangzhou.aliyuncs.com/zm-dev/yzm
    restart: always
    expose:
      - "8080"